categories:
  - title: "🚀新增功能 Features"
    labels:
      - "feat"
      - "enhancement"
  - title: "🐛修复问题 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "🔧优化 Improvement"
    lables:
      - "refactor"
      - "refact"
      - "perf"
  - title: "🧰维护 Maintenance"
    labels:
      - "style"
      - "test"
      - "build"
      - "ci"
      - "chore"
  - title: "📝文档 documents"
    label: "docs"

change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
template: |
  ## 更新日志(Change Log)

  $CHANGES
