name: PR-Docker for preview and test

on:
  pull_request:
    branches:
      - master

jobs:
  docker-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and push Docker images
        uses: docker/build-push-action@v1.1.0
        with:
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
            registry: docker.pkg.github.com
            repository: newfuture/ddns/preview-ddns
            tag_with_ref: true 
            add_git_labels: true